spring:
  application:
    name: accommodation-marketplace
  config:
    import: optional:file:.env[.properties]


  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/employee2_db}
    user: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    show-sql: true
    open-in-view: false
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: false









